### PR TITLE
Asyncify

### PR DESCRIPTION
**Pull request by ryanrhee**
Pretty big PR. I tried to make the diffs as bite-size as possible.

This just modernizes the code by using the new async/await features in .NET 4.5 / C# 5.0.

- Use Task.Delay() instead of Thread.Sleep()
- Linear flow for fishing instead of state machine
- CancellationToken API for pause/stop

All this is done without ever blocking the UI thread, thanks to async/await.

### CODE REVIEW

**Comment by Mograine** [comment]
Hello !

Thanks for this great PR. Tested it and it seem to work like a charm.

The only thing bothering me is the first commit, "	Prettify all .cs files" that remove all vertical alignement. Imho, vertical alignement make the code way more readable

**Comment by ryanrhee** [comment]
@Mograine thanks for your feedback. I only changed the indentation because that was the editor defaults, and I didn't want to fight the IDE, I have no preference in the indentation itself. Do you know if there's a way to change visual studio settings so that your preferred indentation style is how Visual Studio auto-indents code?

**Comment by LaBlazer** [comment]
@Mograine IMO the code looks pretty readable even without the alignment, but i agree that it looks nicer with it.
@ryanrhee I think [CodeAlignment](http://www.codealignment.com/Details.html) extension does it, but i've never tried it...

**Comment by Mograine** [comment]
@LaBlazer @ryanrhee Well it's a minor thing in this major PR. As LaBlazer said you can use CodeAlignement but you'll need to use it on each enum if i remember well

If somebody else could test it to check everything is alright it could be merged

**Comment by ryanrhee** [comment]
@LaBlazer that plugin worked OK.
IMO, anything the IDE won't auto-indent is still a pain (and I'm not sure if CodeAlignment does so without reformatting a selection) but I don't have a preference on the style itself.

@Mograine I tested pretty thoroughly; anything in particular you'd like tested explicitly?

**Pull request merged**
