### PR TITLE
Added custom scanning area selection + update 4.1

### PR DESCRIPTION
**Pull request by LaBlazer**
-added custom scan area option (very useful if you don't want to zoom in before fishing, almost every time it catches the fish faster than with automatic area selection)
-added status indicator (just visual thingy)
-added "Costura" dependency for embedding dlls (you don't have to have dll with the executable anymore)
-added "About" button (just basic info w/ link to official webpage)
-set the size of forms to fixed 
-changed forms to singletons to avoid multiple instances of same form (sometimes multiple instances of the same window caused bugs)
-added a lot of other small things (window icons, updated copyright year e.t.c...)
-updated the version to 4.1 (i thought it was a good time to finally update to 4.1, but you can always change it if you dont like it...)
-also changed target framework to 4.0 so it can work on Windows XP (but i don't know if the sound library will)

TODO:
-unify line endings
-update french translation

Notes:
-versions are now changed in application properties (assembly version)
-i had to re-do a lot of code again because of SourceTree messing up my files, so i hope everything is ok...
-also this bot is confirmed working on WIndows 10 :smile: 

Images:
screenshot 2
screenshot 3

EDIT: Made a little tutorial how to use Ultimate Fish Bot :)
[IMAGE ALT TEXT HERE](http://www.youtube.com/watch?v=TA0wO5RsUKY)

### CODE REVIEW

**Comment by LaBlazer** [comment]
Oops, it seems that appveyor can not download the NuGet packages, so i added them in the project...

**Comment by FireEmerald** [comment]
@LaBlazer  Got this error while compiling - is it possible to fix this by default, without to enable the loadFromRemoteSources switch?

```
Error   1   The "Fody.WeavingTask" task failed unexpectedly.
System.TypeInitializationException: The type initializer for 'ContainsTypeChecker' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'file:///D:\Downloads\CSharp\CSharp\packages\Fody.1.26.1\FodyIsolated.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515) ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
```

**Comment by LaBlazer** [comment]
I will try to fix this as soon as i get home from holiadys or when i find wifi somewhere :smile: , i forgot to enable automatic NuGet package restore... 
EDIT: That was the reason why it wasnt passing the AppVeyor build in commit LaBlazer/UltimateFishbot@97479c1393c9b2b83b58fd21c6281102af60ef1d Im sorry for this, but Im new with those NuGet packages

**Comment by mcousins2009** [comment]
Can you make it work with windows 10.  I am not able to open it at all..  please fix it.  Plus it needs an update  for the new tanaan jungle bait as well

**Comment by LaBlazer** [comment]
As you can see on the pictures, im running it on windows 10 without problems... Have you tried compiling it yourself on w10? If not, I can upload it compiled somewhere... Also make sure you have .NET framework 4.0 and 4.5 installed.

**Comment by Lanzon** [comment]
Pretty new to this. Trying to build in VS 14 but can't get it to work.  "An attempt to load an assembly from a network location..."  Fody.weaving.task failed. 

Think you can help me? Or upload it compiled?

**Comment by LaBlazer** [comment]
Can you give me the full error? Im compilling this on vs13 and it works fine... Ill have to fix this though, because it doesnt work for a lot of people and some people say it does not work on win10 for them...

**Comment by Lanzon** [comment]
Severity    Code    Description Project File    Line
Error       The "Fody.WeavingTask" task failed unexpectedly.
System.TypeInitializationException: The type initializer for 'ContainsTypeChecker' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'file:///C:\Users\Kristian\Downloads\UltimateFishbot-CSharp\packages\Fody.1.26.1\FodyIsolated.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515) ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.

   --- End of inner exception stack trace ---
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile, Evidence securityEvidence)
   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)
   at System.AppDomain.CreateInstanceFromAndUnwrap(String assemblyName, String typeName)
   at System.AppDomain.CreateInstanceFromAndUnwrap(String assemblyName, String typeName)
   at ContainsTypeChecker..cctor() in c:\TeamCity\buildAgent\work\7495521761d392b9\Fody\ContainsTypeChecker.cs:line 16
   --- End of inner exception stack trace ---
   at ContainsTypeChecker..ctor()
   at Processor..ctor() in c:\TeamCity\buildAgent\work\7495521761d392b9\Fody\Processor.cs:line 28
   at Fody.WeavingTask.Execute() in c:\TeamCity\buildAgent\work\7495521761d392b9\Fody\WeavingTask.cs:line 44
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() UltimateFishBot

**Comment by LaBlazer** [comment]
Try closing VS, deleting packages folder and running it again...

**Comment by Lanzon** [comment]
Didn't generate at first. Had to check "Allow Nuget to download missing packages". After that it generated the exact same error.

**Comment by LaBlazer** [comment]
Idk, what can cause this... On appveyor it compiles without problems... Try deleting your project folder and clone it again from my git fork...

**Comment by Lanzon** [comment]
Did that and got another error: 
Severity    Code    Description Project File    Line
Error       Fody: An unhandled exception occurred:
Exception:
Unknown custom metadata item kind: 6
StackTrace:
   at Microsoft.Cci.Pdb.PdbFunction.ReadCustomMetadata(BitAccess bits)
   at Microsoft.Cci.Pdb.PdbFunction..ctor(ManProcSym proc, BitAccess bits)
   at Microsoft.Cci.Pdb.PdbFunction.LoadManagedFunctions(BitAccess bits, UInt32 limit, Boolean readStrings)
   at Microsoft.Cci.Pdb.PdbFile.LoadFuncsFromDbiModule(BitAccess bits, DbiModuleInfo info, IntHashTable names, ArrayList funcList, Boolean readStrings, MsfDirectory dir, Dictionary`2 nameIndex, PdbReader reader)
   at Microsoft.Cci.Pdb.PdbFile.LoadFunctions(Stream read, Dictionary`2& tokenToSourceMapping, String& sourceServerData, Int32& age, Guid& guid)
   at Mono.Cecil.Pdb.PdbReader.PopulateFunctions()
   at Mono.Cecil.Pdb.PdbReader.ProcessDebugHeader(ImageDebugDirectory directory, Byte[] header)
   at Mono.Cecil.ModuleDefinition.ProcessDebugHeader()
   at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader)
   at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
   at Mono.Cecil.ModuleReader.CreateModuleFrom(Image image, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(Stream stream, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at InnerWeaver.ReadModule() in c:\TeamCity\buildAgent\work\7495521761d392b9\FodyIsolated\ModuleReader.cs:line 14
   at InnerWeaver.Execute() in c:\TeamCity\buildAgent\work\7495521761d392b9\FodyIsolated\InnerWeaver.cs:line 28
Source:
Mono.Cecil.Pdb
TargetSite:
Void ReadCustomMetadata(Microsoft.Cci.Pdb.BitAccess)    UltimateFishBot

**Comment by Lanzon** [comment]
Got it working. Upgraded to latest Fody package.

**Comment by Lanzon** [comment]
Though it won't find the bobber. If I don't select area to scan it doesn't search at all. If I do it scans and doesn't find the bobber.

**Comment by Lanzon** [comment]
It is Vanilla wow. So you know.

**Comment by LaBlazer** [comment]
It was not finding the bobber for me too, so i unchecked the Check Cursor Icon option and then it worked... Hope that helps you :) And im glad that you figured out the problem i will update to the latest fody version in my repo too...

**Comment by Lanzon** [comment]
If I uncheck the CHeck Cursor Icon option it won't work at all(doesn't scan for bobber) for me. Running windows 8.1. And if I don't choose scan area the cursor will get stuck in top left corner.

**Comment by LaBlazer** [comment]
That happened to me too, you need to resize the Wow window by +/- 80% and move it to upper left corner... That worked for me until i made the custom area selection..

**Comment by LaBlazer** [comment]
I did not tried to investigate why it didnt work though..

**Comment by Lanzon** [comment]
Yup worked for me. Now I only need it to actually click the bobber when the fish hits.

**Comment by LaBlazer** [comment]
You just need to select the audio device and adjust the "hearing" part... I may do a video tutorial how to set up this fishing bot...

**Comment by Lanzon** [comment]
Hmm. That should probably be good. But it still doesn't work on me. I've tested that it's the right sound device. Tried putting the "sensitivity" down to 1 but that doesn't solve it either.

**Comment by LaBlazer** [comment]
then idk what could it be...

**Comment by Lanzon** [comment]
I'll keep on testing and will update if I find a solution.

**Comment by LaBlazer** [comment]
ok, then... :)

**Pull request merged**
